In [1]:
print("Welcome to Numpy-2")

Welcome to Numpy-2


In [3]:
import numpy as np

In [6]:
a=np.arange(1,13).reshape((3,4))
print(a)
a[:,::-1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [7]:
a=np.arange(1,13).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# gives us the sum of all the values present in the numpy array
np.sum(a)

78

In [9]:
# axis = 1 ---> for horizontal operations 
# in this case calculating the sum for each row

# Method 1
np.sum(a,axis=1)

array([10, 26, 42])

In [10]:
# axis = 0 ---> for vertical operations 
# in this case calculating the sum for each column
np.sum(a,axis=0)

array([15, 18, 21, 24])

In [11]:
# Method 2 
a.sum(axis=1)

array([10, 26, 42])

In [12]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [13]:
# we can calculate mean across rows and columns based on the axis chosen.
np.mean(a,axis=0)

array([5., 6., 7., 8.])

In [14]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [15]:
np.min(a,axis=1)

array([1, 5, 9])

In [16]:
# calculating min values
np.min(a)

1

In [17]:
np.min(a[0])

1

In [19]:
np.mean(a)

6.5

In [20]:
# np.any tries to find out for atleast one non zero value in the array
a=np.array([True,False,True])
np.any(a)

True

In [22]:
b=np.zeros(10)
np.any(b)

False

In [24]:
m=np.array([4,3,2,1])
n=np.array([1,2,3,4])
mask=m<n
mask

array([False, False,  True,  True])

In [25]:
# passing conditions inside np.any to look for atleast 1 non zero value.
np.any(m<n)

True

In [27]:
m=np.array([4,3,2,1])
n=np.array([4,2,3,4])
print(m==n)
np.any(m==n)

[ True False False False]


True

In [28]:
g=np.arange(1,13).reshape((3,4))
h=np.arange(2,14).reshape((3,4))
print(g)
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [29]:
np.any(h<g)

False

In [31]:
np.any(h<10)

True

In [32]:
h<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [33]:
a=np.array([True,False,True])
# no.all returns true if all the values are non zero
# returns False if all the values atleast value is zero
np.all(a)

False

In [34]:
g=np.arange(1,13).reshape((3,4))
h=np.arange(2,14).reshape((3,4))
print(g)
print(h)
np.all(g<h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


True

In [35]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

print(np.all(a==b))

True


In [36]:
a=np.array([[1, 2, 3],
 [4, 6, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

print(np.any(a>b))

True


In [38]:
np.any(a==b)

True

In [39]:
a = np.array([0,2,3]) 
b = np.array([1,3,5])  
# What'll be the output of a >= b?
a >= b

array([False, False, False])

In [40]:
m=np.array([4,3,2,1])
n=np.array([4,2,3,4])
k=np.array([1,1,1,1])
np.any((m<n)|(n>k))

True

In [45]:
np.all((m<n)|(n>k))

True

In [42]:
(m<n)

array([False, False,  True,  True])

In [43]:
(n>k)

array([ True,  True,  True,  True])

In [ ]:
# Sorting


In [51]:
l=np.array([21,30,1,41,7,52,17])
# sorting 1D array
np.sort(l)

array([ 1,  7, 17, 21, 30, 41, 52])

In [52]:
# argsort returns an array of the indexes of sorted elements in the original unsorted array
np.argsort(l)

array([2, 4, 6, 0, 1, 3, 5])

In [53]:

# returns the index of min value element in the array
np.argmin(l)

2

In [54]:
# returns the index of max value element in the array
np.argmax(l)

5

In [60]:
j=np.array([[32,80,12],[3,6,9],[98,75,110]])
print(j)


[[ 32  80  12]
 [  3   6   9]
 [ 98  75 110]]


In [61]:
# we can sort on a chosen axis
# axis=0 sorting will sort columns
np.sort(j,axis=0)

array([[  3,   6,   9],
       [ 32,  75,  12],
       [ 98,  80, 110]])

In [62]:
# axis=0 sorting will sort rows
np.sort(j,axis=1)

array([[ 12,  32,  80],
       [  3,   6,   9],
       [ 75,  98, 110]])

In [63]:
np.sort(j)

array([[ 12,  32,  80],
       [  3,   6,   9],
       [ 75,  98, 110]])

In [64]:
# downloading the dataset
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /Users/nikhilsanghi/Downloads/dsml-course-main-live/June_Intermediate/fitness.txt
100%|██████████████████████████████████████| 3.14k/3.14k [00:00<00:00, 3.65MB/s]


In [65]:
data=np.loadtxt("/Users/nikhilsanghi/Downloads/dsml-course-main-live/June_Intermediate/fitness.txt",dtype="str")

In [66]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [67]:
data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [88]:
# columns 
# date,step_count,mood,calories_burned,hours_of_sleep,bool_active,weight


NameError: name 'calories_burned' is not defined

In [72]:
# date=data[:,0]
# data[:,1]

#Taking a transpose of data to convert each feature into rows 
data=data.T

In [94]:
# unpacking the data

date,step_count,mood,calories_burned,hours_of_sleep,bool_active,weight=data

In [95]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [96]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [97]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [98]:
# converting data type of columns to integer
step_count=np.array(step_count,dtype="int")
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [99]:
calories_burned=np.array(calories_burned,dtype="int")
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [100]:
hours_of_sleep=np.array(hours_of_sleep,dtype="int")
hours_of_sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [101]:
weight=np.array(weight,dtype="int")
weight

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [102]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [103]:
# Changing the categorical values to much more intuitive valuesa
mood[mood == "300"] = "Happy"

mood

In [104]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', 'Happy', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', 'Happy', '200', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', '200',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', '200', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', '200', '100',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       '100', '200', '200', '100', '100', '200', '200', 'Happy', '200',
       '200', '100', '200', '100', '200', '200', '100', '100', '100',
       '100', 'Happy', '200', 'Happy', '200', '100', '100', '100', '200',
       '200', '100', '100', 'Happy', '200', '200', 'Happy'], dtype='<U10')

In [105]:
mood[mood == "100"] = "Sad"

In [106]:
mood[mood == "200"] = "Neutral"

In [107]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [108]:
bool_active[bool_active == "500"] = "Active"

In [109]:
bool_active[bool_active == "0"] = "Inactive"

In [110]:
bool_active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [111]:
mood.dtype

dtype('<U10')

In [112]:
# calculating the mean of steps that person took.
np.mean(step_count)

2935.9375

In [114]:
# trying to find out the date on which the person took maximum number of steps.
date[np.argmax(step_count)]

'14-12-2017'

In [115]:
date[step_count==7422]

array(['14-12-2017'], dtype='<U10')

In [116]:
# trying to find out the date on which the person took minimum number of steps.
date[np.argmin(step_count)]

'08-10-2017'

In [117]:
# trying to find out the calories burned on a day on which the person took maximum number of steps.
calories_burned[np.argmax(step_count)]

243

In [118]:
np.max(calories_burned)

243

In [119]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [121]:
mood[mood == "Happy"].shape

(40,)

In [122]:
mood[mood == "Sad"].shape

(29,)

In [123]:
mood[mood == "Neutral"].shape

(27,)

In [124]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [131]:
# trying to find out the frequency of each unique values in the mood columns

np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [127]:
np.unique(bool_active,return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [132]:
np.mean(step_count[mood=="Happy"])

3392.725

In [133]:
np.mean(step_count[mood=="Sad"])

2103.0689655172414

In [134]:
np.mean(step_count[mood=="Neutral"])

3153.777777777778

In [135]:
# calculating freq of mood where the number of steps taken is more than 4000
np.unique(mood[step_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [136]:
np.unique(mood[step_count<2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

In [137]:
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a)

In [138]:
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [140]:
a=[[1 ,2 ,3],
[4 ,5, 6],
[7 ,8, 9]]
print(np.max(a, axis=0))



[7 8 9]


In [141]:
a=np.array([1,2,3])
b=np.array([2,3,4])
a+b

array([3, 5, 7])

In [142]:
np.add(a,b)

array([3, 5, 7])

In [144]:
m=np.arange(1,13).reshape((3,4))
n=np.arange(2,14).reshape((3,4))
m*n

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [145]:
# obtaining matrix multiplication result of 2 arrays
# Method 1
np.matmul(m,n)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [146]:
m=np.arange(1,13).reshape((3,4))
n=np.arange(2,14).reshape((4,3))
np.matmul(m,n)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [147]:
np.matmul(n,m)

array([[ 53,  62,  71,  80],
       [ 98, 116, 134, 152],
       [143, 170, 197, 224],
       [188, 224, 260, 296]])

In [148]:
# Method 2
n@m

array([[ 53,  62,  71,  80],
       [ 98, 116, 134, 152],
       [143, 170, 197, 224],
       [188, 224, 260, 296]])

In [149]:
# Method 1
# Better and preferred
np.dot(n,m)

array([[ 53,  62,  71,  80],
       [ 98, 116, 134, 152],
       [143, 170, 197, 224],
       [188, 224, 260, 296]])

In [150]:
a=np.array([1,2,3])
b=np.array([2,3,4])
np.matmul(a,b)

20

In [151]:
np.matmul(4,5)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [152]:
np.dot(a,b)

20

In [154]:
np.dot(3,2)

6

In [155]:
a@b

20

In [156]:
4@5

TypeError: unsupported operand type(s) for @: 'int' and 'int'

In [157]:
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
a=np.array([1,2,3])
a.shape

(3,)

In [160]:
m*a

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [161]:
np.matmul(m,a)

array([14, 32, 50])

In [162]:
np.matmul(a,m)

array([30, 36, 42])

In [163]:
np.dot(m,a)

array([14, 32, 50])

In [164]:
np.dot(a,m)

array([30, 36, 42])

In [166]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b

c = c*a
print(c)
# print (c[2])

[ 1 10 21 35 72]


In [167]:
import math
a = np.array([1,2,3,5,8])
print(a)


[1 2 3 5 8]


In [170]:
# we can vercotize any function on work on each element of numpy array.
func=np.vectorize(math.log)
func(a)

array([0.        , 0.69314718, 1.09861229, 1.60943791, 2.07944154])

In [172]:
def cube(s):
    return s**3
func1=np.vectorize(cube)
func1(a)

array([  1,   8,  27, 125, 512])

In [173]:
a=np.arange(1,13).reshape((3,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [174]:
# creating multiple copies of the same data by creating tiles and replicating it across rows and columns
np.tile(a,(2,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [175]:
np.tile(a,(3,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [177]:
a = np.arange(1,100000)
b = np.ones(100000)
# %timeit a.any()
# %timeit b.any()

In [178]:

print(a)

[    1     2     3 ... 99997 99998 99999]


In [179]:
print(b)

[1. 1. 1. ... 1. 1. 1.]


In [180]:
%timeit np.any(a)

31 µs ± 559 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [181]:
%timeit np.any(b)

32.1 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [186]:
a=np.arange(1,11).reshape(-1,-1)
a

ValueError: can only specify one unknown dimension

In [ ]:
()