In [3]:
import numpy as np

In [4]:
a=[1,2,3,4,5]
print([i**2 for i in a])

[1, 4, 9, 16, 25]


In [6]:
# we can create numpy arrays using np.array
b=np.array([1,2,3,4,5])
print(b**2)

[ 1  4  9 16 25]


In [8]:
# numpy supports elementwise operations
print(b+2)

[3 4 5 6 7]


In [9]:
c=np.array(a)
print(c)

[1 2 3 4 5]


In [10]:
# type of the entire Numpy array
type(a)

list

In [11]:
type(b)

numpy.ndarray

In [12]:
l=range(10000)


In [13]:
%timeit [i**2 for i in l]

2.51 ms ± 46.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
m=np.arange(10000)
print(m)

[   0    1    2 ... 9997 9998 9999]


In [15]:
%timeit m**2

3.59 µs ± 32.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
c=np.array([1,2,3])
print(type(c))
# data type of elements of the numpy array
c.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [22]:
# because of one element 4.5 , every element's dtype has been type casted into float
c=np.array([1,2,3,4.5])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
[1.  2.  3.  4.5]


dtype('float64')

In [24]:
# because of one element 4.5 , every element's dtype has been type casted into string
c=np.array([1,2,3,"c"])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
['1' '2' '3' 'c']


dtype('<U21')

In [25]:
c=np.array([1,2,3,"4.5",3.9])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
['1' '2' '3' '4.5' '3.9']


dtype('<U32')

In [30]:
# booleans are treated as 1 and 0 for True and False respectively
c=np.array([1,1,0,True,False])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
[1 1 0 1 0]


dtype('int64')

In [31]:
b=np.array([1,2,3,4,5])
# used to find out the dimension of the array
b.ndim

1

In [32]:
# used to find out the shape of the numpy array
b.shape

(5,)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

In [34]:
# range function generates numbers for start to end(excluded) with some step size
# range( start, stop,step_size)
f=range(0,10,1)
print(f)

range(0, 10)


In [37]:
# arange function in numpy generates numbers for start to end(excluded) with some step size
# arange( start, stop,step_size)
# arange is different from range --> we can give floats as step size
g=np.arange(0,10,0.67)
print(g)

[0.   0.67 1.34 2.01 2.68 3.35 4.02 4.69 5.36 6.03 6.7  7.37 8.04 8.71
 9.38]


In [38]:
# linspace is used to create equally spaced numbers between start and end both included.
start,end,flag_count=0,100,25
np.linspace(start,end,flag_counts)

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [42]:
f=np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [43]:
# creating a 2d numpy Array
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
m.shape

(2, 3)

In [45]:
m.ndim

2

In [47]:
a = np.array([1,2,3,4,5,6,7,8])
len(a)

8

In [48]:
len(m)

2

In [49]:
m2=np.arange(1,13)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
m2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
# here we knew that we want 2 rows, but not the columns, so we passed -1 as the parameter. 
# numpy will automatically find out the required number of columns it need to display the data.
m2.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
m2.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
# we need to pass atleast one dimension
m2.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [55]:
m2.reshape(5,-1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [58]:
m2=np.arange(1,13)
#reshape functions reshapes the arrays into the shape of (rows and columns) we define
m2=m2.reshape(3,4)


In [59]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
m3=np.arange(1,14)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [62]:
m3.reshape(3,4)

ValueError: cannot reshape array of size 13 into shape (3,4)

In [63]:
m4=np.array([[1,2,3],[4,5,6,8,0,9]])
m4

/var/folders/hd/9z4dczb56dj54lb7q8w7s4zw0000gn/T/ipykernel_41514/3277800209.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m4=np.array([[1,2,3],[4,5,6,8,0,9]])


array([list([1, 2, 3]), list([4, 5, 6, 8, 0, 9])], dtype=object)

In [65]:
m3=np.arange(1,14)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [66]:
m3.reshape(1,13)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [67]:
m3.reshape(13,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [68]:
m3.reshape(2,-1)

ValueError: cannot reshape array of size 13 into shape (2,newaxis)

In [ ]:

a = np.arange(1,17).reshape(-1,2)
a.shape

In [70]:

a = np.arange(1,17).reshape(-1,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [71]:
m4=np.arange(1,7)
m4

array([1, 2, 3, 4, 5, 6])

In [73]:
m5=m4.reshape(2,3)
print(m5)

[[1 2 3]
 [4 5 6]]


In [74]:
m5.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
m4=np.arange(1,13).reshape(6,2)
print(m4)
# .T creates a transpose of a matrix rows--> columns, columns--> rows
# converting rows into columns.
m4.T

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [76]:
m5=np.arange(3).reshape(1,3)
m5.ndim

2

In [77]:
m5.shape

(1, 3)

In [79]:
m5.T.shape

(3, 1)

In [81]:
m6=np.array([1,2,3])
m6.shape

(3,)

In [82]:
m6.ndim

1

In [83]:
m6.T

array([1, 2, 3])

In [84]:
m6=np.array([[1,2,3]])
m6.shape

(1, 3)

In [85]:
m6.ndim

2

In [86]:
m6.T

array([[1],
       [2],
       [3]])

In [87]:
m7=np.arange(1,13).reshape(3,4)
m7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
m7.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# creating special arrays

In [89]:
# creating 1D array with all the values as 0
np.zeros(3)

array([0., 0., 0.])

In [90]:
# creating 2D array  of shape (3,3) with all the values as 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
# creating 2D array  of shape (3,) with all the values as 1

np.ones(3)

array([1., 1., 1.])

In [93]:
# creating 2D array  of shape (6,2) with all the values as 1
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [97]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [98]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [99]:
a*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [102]:
a=np.ones((3,3),dtype=np.int32)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [104]:
# creating 2D array  of shape (3,3) with all the values as 4.0
np.full((3,3),4.0)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [105]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1,2,3 and rest as 0
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
#indexing

In [111]:
m1=np.arange(3,10)
m1

array([3, 4, 5, 6, 7, 8, 9])

In [112]:
#accessing the data
m1[0]

3

In [113]:
m1[1]

4

In [115]:
# we can access using negative indexes
m1[-1]

9

In [116]:
m1[-2]

8

In [117]:
m1[-7]

3

In [114]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
# method - 1, for accessing elements
m2[1][1]

6

In [119]:
# method - 2, for accessing elements ( Preferred )
m2[1,1]

6

In [121]:
m7=np.array([100,100,300,400,500,600])
m7

array([100, 100, 300, 400, 500, 600])

In [123]:
# We can pass a list of indexes of the elements we want to access 
m7[[2,4,5,4]]

array([300, 500, 600, 500])

In [124]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
# to access multiple elements, we need to pass the row and column indexes separately in lists.
m2[[1,1,2],[1,3,3]]

array([ 6,  8, 12])

In [126]:
# we cannot pass each elements separately.
# m2[[1,1],[1,3],[2,3]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [132]:
m8=np.arange(1,13)

In [136]:
m8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [137]:
# slicing elements from a numpy array.
m8[:5]

array([1, 2, 3, 4, 5])

In [138]:
m8[7:]

array([ 8,  9, 10, 11, 12])

In [139]:
# slicing elements from a numpy array using step size
m8[1::2]

array([ 2,  4,  6,  8, 10, 12])

In [140]:
m8[1::3]

array([ 2,  5,  8, 11])

In [142]:
# we can pass negative step sizes as well
m8[-11:-5]

array([2, 3, 4, 5, 6, 7])

In [143]:
m8[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [144]:
m8[2:5:-1]

array([], dtype=int64)

In [145]:
m8[5:2:-1]

array([6, 5, 4])

In [147]:
m9=np.arange(1,13).reshape(3,4)

In [148]:
m9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
m9[0]

array([1, 2, 3, 4])

In [150]:
m9[0][1:3]

array([2, 3])

In [151]:
# accessing 0th indexed row and columns of indexes 1 and 2
m9[0,1:3]

array([2, 3])

In [153]:

# slicing multiple rows and columns
m9[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [154]:
m9[1:,:2]

array([[ 5,  6],
       [ 9, 10]])

In [155]:
m9[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [157]:
# if we want to access specific columns of rows, we pass the index within a list or tuple. both works
# m9[:,[0,1,2]] it also works the same way

m9[:,(0,1,2)]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2 : ] = b[ : : -1]


In [158]:
a = [1,2,3,4,5]

In [159]:
b = [8,7,6]

In [160]:
a[2 : ] = b[ : : -1]

In [161]:
a

[1, 2, 6, 7, 8]

In [162]:
a[3]=100

In [163]:
a

[1, 2, 6, 100, 8]

In [164]:
m1 = np.array([[0,1,2,3],
[4,5,6,7],
[8,9,10,11]])

m1[0,1:3]

array([1, 2])

In [165]:
a = np.array([0,1,2,3,4,5])
a[4:]=10
a

array([ 0,  1,  2,  3, 10, 10])

In [168]:
m1=np.arange(1,13).reshape(3,4)
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
# numpy also supports elements logical operations.
# here we are creating mask of boolean values.
mask=m1<6
mask

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [170]:
m1[mask]

array([1, 2, 3, 4, 5])

In [174]:
# filtering out the values that satisfies the condition or the values where we have True as value.
m1[m1%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [175]:
# creating multiple conditions.
mask=(m1%2==0)|(m1%5==0) 

In [176]:
mask

array([[False,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

In [177]:
m1[mask]

array([ 2,  4,  5,  6,  8, 10, 12])

In [178]:
m1%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [179]:
m1%5==0

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [181]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
mask
a[mask] = -1
# What'll be the values of a?

In [182]:
a

array([-1,  1, -1,  3, -1,  5])

In [185]:
np.eye?

In [190]:
np.eye(10,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [189]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [191]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])